version: 1.0.{build}
image: Visual Studio 2017
platform: x64
configuration: Debug

before_build:
  - nuget install packages.config
  - dotnet restore

build:
  include_nuget_references: true
  verbosity: normal
  project: TestFromNuget.sln 

